// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUUBcb5dG6fuvhoT-4pGBfDUZZC9ExKE',
    appId: '1:439688268898:web:ba7da427f61b98faf0153b',
    messagingSenderId: '439688268898',
    projectId: 'ex2-task2',
    authDomain: 'ex2-task2.firebaseapp.com',
    storageBucket: 'ex2-task2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWHcwGEq1O-a38Xm003crxcH5W5Okhxz0',
    appId: '1:439688268898:android:881f72c699d7420ff0153b',
    messagingSenderId: '439688268898',
    projectId: 'ex2-task2',
    storageBucket: 'ex2-task2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVoICZo2u35kFw-mnSnEYwuYhsX2OhDHY',
    appId: '1:439688268898:ios:ff8fbf2e8ad70aecf0153b',
    messagingSenderId: '439688268898',
    projectId: 'ex2-task2',
    storageBucket: 'ex2-task2.firebasestorage.app',
    iosBundleId: 'com.example.ex2Task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVoICZo2u35kFw-mnSnEYwuYhsX2OhDHY',
    appId: '1:439688268898:ios:ff8fbf2e8ad70aecf0153b',
    messagingSenderId: '439688268898',
    projectId: 'ex2-task2',
    storageBucket: 'ex2-task2.firebasestorage.app',
    iosBundleId: 'com.example.ex2Task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhUUBcb5dG6fuvhoT-4pGBfDUZZC9ExKE',
    appId: '1:439688268898:web:ff2df26545357096f0153b',
    messagingSenderId: '439688268898',
    projectId: 'ex2-task2',
    authDomain: 'ex2-task2.firebaseapp.com',
    storageBucket: 'ex2-task2.firebasestorage.app',
  );
}
