// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1RXC1gzg-mTSFQ833nmb03hWD9bTgxf4',
    appId: '1:407104376720:web:9f9c9dbf993aa8d8352d15',
    messagingSenderId: '407104376720',
    projectId: 'restaurantapp-4635d',
    authDomain: 'restaurantapp-4635d.firebaseapp.com',
    storageBucket: 'restaurantapp-4635d.firebasestorage.app',
    measurementId: 'G-DCHLTKBC45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7FJq1N41mFHo90bzBvOJstmo0Xf_kp8',
    appId: '1:407104376720:android:37ff71722116a56b352d15',
    messagingSenderId: '407104376720',
    projectId: 'restaurantapp-4635d',
    storageBucket: 'restaurantapp-4635d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdZin-QYuGLAR8X5M-N61mL5rY2Qe5iw',
    appId: '1:407104376720:ios:1cf219c418640db3352d15',
    messagingSenderId: '407104376720',
    projectId: 'restaurantapp-4635d',
    storageBucket: 'restaurantapp-4635d.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTdZin-QYuGLAR8X5M-N61mL5rY2Qe5iw',
    appId: '1:407104376720:ios:1cf219c418640db3352d15',
    messagingSenderId: '407104376720',
    projectId: 'restaurantapp-4635d',
    storageBucket: 'restaurantapp-4635d.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1RXC1gzg-mTSFQ833nmb03hWD9bTgxf4',
    appId: '1:407104376720:web:17cf089fe6ea5aa7352d15',
    messagingSenderId: '407104376720',
    projectId: 'restaurantapp-4635d',
    authDomain: 'restaurantapp-4635d.firebaseapp.com',
    storageBucket: 'restaurantapp-4635d.firebasestorage.app',
    measurementId: 'G-DV6F963ZB8',
  );
}
