// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBKz4n4Mey2WxG1uvUjfmJSLwaurpdGB4',
    appId: '1:904803229415:web:beb517ea9df6fa4823cc42',
    messagingSenderId: '904803229415',
    projectId: 'myapp-362f1',
    authDomain: 'myapp-362f1.firebaseapp.com',
    storageBucket: 'myapp-362f1.firebasestorage.app',
    measurementId: 'G-KEPMVQNTBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSflYUWdEq01TcfM1JSp4MKze96s3S2k',
    appId: '1:904803229415:android:a6775df5d9973b8223cc42',
    messagingSenderId: '904803229415',
    projectId: 'myapp-362f1',
    storageBucket: 'myapp-362f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQWwkD404gj9La39Kg8QVGhkQQqXGnCtw',
    appId: '1:904803229415:ios:923a5b854c53b8d323cc42',
    messagingSenderId: '904803229415',
    projectId: 'myapp-362f1',
    storageBucket: 'myapp-362f1.firebasestorage.app',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQWwkD404gj9La39Kg8QVGhkQQqXGnCtw',
    appId: '1:904803229415:ios:923a5b854c53b8d323cc42',
    messagingSenderId: '904803229415',
    projectId: 'myapp-362f1',
    storageBucket: 'myapp-362f1.firebasestorage.app',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBKz4n4Mey2WxG1uvUjfmJSLwaurpdGB4',
    appId: '1:904803229415:web:f5053a3e2e89af4023cc42',
    messagingSenderId: '904803229415',
    projectId: 'myapp-362f1',
    authDomain: 'myapp-362f1.firebaseapp.com',
    storageBucket: 'myapp-362f1.firebasestorage.app',
    measurementId: 'G-C26S2LHL60',
  );

}